### PR TITLE
use glibc 2.22 to work around assembler error

### PR DESCRIPTION
**Pull request by csmart**
@shenki after our buildroot was seemingly re-worked from upstream master, initramfs builds have been failing[1] on openpower.xyz.

```
03:57:49 ../sysdeps/unix/sysv/linux/powerpc/powerpc64/setcontext.S: Assembler messages:
03:57:49 ../sysdeps/unix/sysv/linux/powerpc/powerpc64/setcontext.S:367: Error: junk at end of line: `1,0'
```

They work fine if I build with glibc 2.22 instead of 2.21 however, so this PR adds this specification to the openpower config we're creating. Builds now succeeding[2].

[1] https://openpower.xyz/job/initramfs-build/9/console
[2] https://openpower.xyz/job/initramfs-build/12/

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/openbmc-build-scripts/8)

### CODE REVIEW

**Comment by shenki** [comment]
Why are we building master from open-power's buildroot? That branch has no value to us; it might point to somewhere upstream.

The way we use the buildroot repository in open-power is to have a branch from upstream's releases, and on top of that apply a few patches in order to add features we require, or bring in support for newer versions of packages by backporting upstream commits.

I think this job would serve it's purpose better by tracking upstream, or upstream stable releases.

**Comment by csmart** [comment]
OK, so we should just use actual upstream buildroot? I guess we used this one because it had specific fixes on top of upstream to make things work while they were fixed upstream.

**Comment by shenki** [comment]
Yeah, as it turns out the fixes we carry aren't all that interesting in isolation from the open-power overlay, particularly as we're not building pnor images.

Lets track upstream; it will give us coverage of their development cycle, allowing us to be confident that new upstream releases will work on power.

Do you want to see if upstream is interesting in taking a powernv_le defconfig?

**Comment by csmart** [comment]
Actually, I just found configs/powerpc64_openpower_defconfig in my local upstream buildroot git repo, so I probably just had a brainfart when I was configuring the jenkins job. I've set that job to use upstream buildroot now.

Having said that, this patch is still required.

Yeah I'll have a look at getting a defconfig upstream separately.

**Comment by shenki** [comment]
Cool, thank you!

Let me know if you want me to find someone to do the defconfig upstreaming. Feel free to chat about what kind of things we want to enable too.

**Comment by williamspatrick** [comment]
What is this even doing? I'm lost why we are building buildroot configs in a repository called "openbmc-build-scripts". It doesn't seem, from my cursory glance, that this is building a full host side flash image for barreleye or palmetto.

**Comment by csmart** [comment]
@williamspatrick I think it's meant to just be a way to conveniently provide a basic initramfs for partners to grab for testing.

**Comment by williamspatrick** [comment]
But why is it in the openbmc project code repository?

**Comment by csmart** [comment]
@williamspatrick ahh right, cause we already had builds scripts here, I guess. Should I move it to open-power or something?

**Comment by shenki** [comment]
@williamspatrick it's here because it grew out of openpower.xyz, which is/was a OpenBMC thing.

I'm happy that we're doing CI, and doing it in the public, and the scripts have some form of configuration management. They can say here for now

**Comment by csmart** [comment]
@shenki you happy to merge this then? We can look at splitting out later.

**Pull request merged**
