### PR TITLE
Add docs-build script

### PR DESCRIPTION
**Pull request by jk-ozlabs**
This change adds a script to build the OpenBMC docs repo, which can
produce a User Guide PDF.

Signed-off-by: Jeremy Kerr <jk@ozlabs.org>

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/openbmc-build-scripts/9)

### CODE REVIEW

**Comment by causten** [comment]
our docs repo runs docker.  I love it

**Comment by causten** [comment]
:lgtm:

<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> our docs repo runs docker.  I love it
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc-build-scripts/9#-:-KIfN8RXJ-lg9RB9nHcu:1417088721)*

**Comment by shenki** [comment]
Thanks @jk-ozlabs.

Do we want to hook this up to traivs as well?

**Comment by jk-ozlabs** [comment]
@shenki: I think just to the CI builds on openpower.xyz, so we can get the PDF built automatically.

**Comment by jk-ozlabs** [comment]
Woooooooot: https://openpower.xyz/job/openbmc-docs/lastSuccessfulBuild/artifact/userguide.pdf

**Pull request merged**
